install.packages("ggplot2", dependencies = TRUE)
install.packages("plyr")
install.packages("caret")
install.packages("reshape2")
install.packages("MASS")
install.packages("ggcorrplot")
install.packages("plotmo")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("e1071")
install.packages("class")
install.packages("dplyr")
install.packages("data.table")
